"""Stable enumerations used by APIs, persistence and workflows."""

from enum import IntEnum, StrEnum


class CognitiveLevel(IntEnum):
    INTUITIVE_RECOGNITION = 1
    GUIDED_IMITATION = 2
    CONCEPTUAL_UNDERSTANDING = 3
    INDEPENDENT_APPLICATION = 4
    CRITICAL_TRANSFER = 5
    CREATION_RESEARCH = 6


class EpistemicStatus(StrEnum):
    CONFIRMED = "CONFIRMED"
    PROPOSED = "PROPOSED"
    INFERRED = "INFERRED"
    USER_SUPPLIED = "USER_SUPPLIED"
    UNVERIFIED = "UNVERIFIED"
    DISPUTED = "DISPUTED"
    SUPERSEDED = "SUPERSEDED"


class RelationTypeKey(StrEnum):
    IS_A = "IS_A"
    PART_OF = "PART_OF"
    REQUIRES = "REQUIRES"
    ENABLES = "ENABLES"
    EXPLAINS = "EXPLAINS"
    CONTRASTS_WITH = "CONTRASTS_WITH"
    SIMILAR_TO = "SIMILAR_TO"
    APPLIES_TO = "APPLIES_TO"
    FAILS_WHEN = "FAILS_WHEN"
    SUPPORTED_BY = "SUPPORTED_BY"
    DERIVED_FROM = "DERIVED_FROM"
    EXAMPLE_OF = "EXAMPLE_OF"
    COUNTEREXAMPLE_OF = "COUNTEREXAMPLE_OF"
    MISCONCEPTION_ABOUT = "MISCONCEPTION_ABOUT"
    ASSESSES = "ASSESSES"
    TEACHES = "TEACHES"
    MASTERED_BY = "MASTERED_BY"
    SUPERSEDES = "SUPERSEDES"
    CONFLICTS_WITH = "CONFLICTS_WITH"


class NodeType(StrEnum):
    ENTITY_TYPE = "EntityType"
    RELATION_TYPE = "RelationType"
    CONSTRAINT = "Constraint"
    THEORY = "Theory"
    DOMAIN = "Domain"
    EPISTEMIC_STATUS = "EpistemicStatus"
    KNOWLEDGE_POINT = "KnowledgePoint"
    DEFINITION = "Definition"
    METHOD = "Method"
    EXAMPLE = "Example"
    COUNTEREXAMPLE = "Counterexample"
    MISCONCEPTION = "Misconception"
    QUESTION = "Question"
    LEARNING_STAGE = "LearningStage"
    SOURCE_DOCUMENT = "SourceDocument"
    SOURCE_SPAN = "SourceSpan"
    LEARNER = "Learner"
    LEARNER_KNOWLEDGE_STATE = "LearnerKnowledgeState"
    MASTERY_EVIDENCE = "MasteryEvidence"
    ERROR_PATTERN = "ErrorPattern"
    LEARNING_GOAL = "LearningGoal"
    SESSION = "Session"
    CONFLICT_SET = "ConflictSet"
    RELATION_ASSERTION = "RelationAssertion"


class EvidenceType(StrEnum):
    RECOGNITION = "RECOGNITION"
    WORKED_EXAMPLE = "WORKED_EXAMPLE"
    EXPLANATION = "EXPLANATION"
    APPLICATION = "APPLICATION"
    TRANSFER = "TRANSFER"
    CRITIQUE = "CRITIQUE"
    CREATION = "CREATION"
    SELF_REPORT = "SELF_REPORT"


class MasteryDecision(StrEnum):
    PROMOTE = "PROMOTE"
    HOLD = "HOLD"
    REMEDIATE = "REMEDIATE"
    REVIEW_PREREQUISITE = "REVIEW_PREREQUISITE"
    CHANGE_EXPLANATION = "CHANGE_EXPLANATION"
    REQUEST_MORE_EVIDENCE = "REQUEST_MORE_EVIDENCE"


class TeachingAction(StrEnum):
    DIAGNOSE = "DIAGNOSE"
    EXPLAIN_INTUITIVELY = "EXPLAIN_INTUITIVELY"
    DEMONSTRATE = "DEMONSTRATE"
    EXPLAIN_CAUSALLY = "EXPLAIN_CAUSALLY"
    GUIDE_APPLICATION = "GUIDE_APPLICATION"
    CHALLENGE_WITH_BOUNDARY = "CHALLENGE_WITH_BOUNDARY"
    FORMULATE_RESEARCH_QUESTION = "FORMULATE_RESEARCH_QUESTION"
    GIVE_HINT = "GIVE_HINT"
    REMEDIATE = "REMEDIATE"
    REVIEW_PREREQUISITE = "REVIEW_PREREQUISITE"
    ASSESS = "ASSESS"
    SUMMARIZE_PROGRESS = "SUMMARIZE_PROGRESS"


class HintLevel(IntEnum):
    LEVEL_1_DIRECTION = 1
    LEVEL_2_MISSING_CONDITION = 2
    LEVEL_3_STRUCTURE = 3
    LEVEL_4_PARTIAL_SOLUTION = 4
    LEVEL_5_FULL_DEMONSTRATION = 5


class AssessmentType(StrEnum):
    RECOGNIZE = "RECOGNIZE"
    REPRODUCE_PROCEDURE = "REPRODUCE_PROCEDURE"
    EXPLAIN_REASON = "EXPLAIN_REASON"
    APPLY = "APPLY"
    ANALYZE_BOUNDARY = "ANALYZE_BOUNDARY"
    DESIGN_RESEARCH = "DESIGN_RESEARCH"


class RequestedMode(StrEnum):
    LEARN = "learn"
    REVIEW = "review"
    EXAM = "exam"
    PRACTICE = "practice"
    RESEARCH = "research"


class DocumentStatus(StrEnum):
    UPLOADED = "UPLOADED"
    PARSING = "PARSING"
    INGESTED = "INGESTED"
    FAILED = "FAILED"


class InputKind(StrEnum):
    TEXT = "TEXT"
    PDF = "PDF"
    DOCUMENT = "DOCUMENT"
    PRESENTATION = "PRESENTATION"
    IMAGE = "IMAGE"


class GraphRevisionStatus(StrEnum):
    PENDING = "PENDING"
    APPLIED = "APPLIED"
    FAILED = "FAILED"


class ConflictType(StrEnum):
    TEMPORAL_REPLACEMENT = "TEMPORAL_REPLACEMENT"
    COMPETING_OBJECT = "COMPETING_OBJECT"
    EPISTEMIC_DISAGREEMENT = "EPISTEMIC_DISAGREEMENT"
    DUPLICATE_ASSERTION = "DUPLICATE_ASSERTION"
